django_training/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import quiz.urls
import quiz2.urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include(quiz.urls)),
    url(r'^', include(quiz2.urls))
]

quiz/urls.py
from django.conf.urls import url
from .views import QuestionView, \
    QuestionDetailView, QuestionResultView, \
    answer_choices, QuestionDeleteView

app_name = 'quiz'
urlpatterns = [
    url(
        r'^questions/$',
        QuestionView.as_view(),
        name="index"),
    url(
        r'^questions/(?P<pk>\d+)/$',
        QuestionDetailView.as_view(),
        name="detail"),
    url(
        r'^questions/(?P<pk>\d+)/delete/$',
        QuestionDeleteView.as_view(),
        name="delete"),
    url(
        r'^questions/(?P<pk>\d+)/choice/$',
        answer_choices,
        name="choice"),
    url(
        r'^questions/(?P<pk>\d+)/result/$',
        QuestionResultView.as_view(),
        name="result"),
]

quiz2/urls.py
from django.conf.urls import url
from .views import question_detail, question_list, question_delete

app_name = 'quiz2'
urlpatterns = [
    url(r'^questions2/$', question_list, name="index"),
    url(r'^questions2/(?P<pk>\d+)/$', question_detail, name="detail"),
    url(r'^questions2/(?P<pk>\d+)/delete/$', question_delete, name="delete")
]

quiz/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField


class Question(models.Model):
    text = models.CharField(max_length=200)
    answer_choices = JSONField()

    def correct_answer_choice_ids(self):
        return (c["id"] for c in self.answer_choices if c["correct"])

    def is_answer_choice_id_correct(self, answer_choice_id):
        return answer_choice_id in self.correct_answer_choice_ids()

quiz2/models.py
from django.db import models
from django.contrib.postgres.fields import JSONField


class Question(models.Model):
    text = models.CharField(max_length=200)
    answer_choices = JSONField()

    def correct_answer_choice_ids(self):
        return (c["id"] for c in self.answer_choices if c["correct"])

    def is_answer_choice_id_correct(self, answer_choice_id):
        return answer_choice_id in self.correct_answer_choice_ids()

quiz/forms.py
from django import forms


class AnswerChoiceForm(forms.Form):
    text = forms.CharField(label='Answer Text', max_length=100)
    correct = forms.BooleanField(initial=False, required=False)

quiz2/forms.py
from django import forms
from django.contrib.postgres.forms import JSONField
from .models import Question
from .serializers import AnswerChoiceSerializer


class QuestionForm(forms.ModelForm):
    answer_choices = JSONField(initial=[
        {"id": 1, "text": "a", "correct": True},
        {"id": 2, "text": "b", "correct": False},
        {"id": 3, "text": "c", "correct": False},
        {"id": 4, "text": "d", "correct": False}
    ])

    class Meta:
        model = Question
        fields = ("text", "answer_choices")

    def clean_answer_choices(self):

        if len(self.cleaned_data["answer_choices"]) != 4:
            raise forms.ValidationError("Answer Choices length is not 4")

        answer_choices_serializer = AnswerChoiceSerializer(
            data=self.cleaned_data["answer_choices"], many=True)
        if not answer_choices_serializer.is_valid():
            raise forms.ValidationError(str(answer_choices_serializer.errors))

        answer_choices = []
        for idx, answer_choice in enumerate(answer_choices_serializer.data):
            answer_choices.append(dict(answer_choice, id=idx))

        return answer_choices

quiz/views.py
from django.views import generic
from django.http import HttpResponseRedirect
from django.shortcuts import render
from .forms import AnswerChoiceForm
from django.forms import formset_factory
from django.urls import reverse, reverse_lazy
from .models import Question


class QuestionView(generic.ListView):
    """
    List Questions
    Post New Question - Redirect to Question Detail
    """
    template_name = 'index.html'
    context_object_name = 'questions'
    queryset = Question.objects.all()

    def post(self, request, *args, **kwargs):
        question = Question.objects.create(
            text=request.POST["text"],
            answer_choices={})
        return HttpResponseRedirect(
            reverse('quiz:detail', args=(question.id,)))


class QuestionDetailView(generic.DetailView):
    """
    Question Details
    """
    template_name_field = 'question'
    model = Question


class QuestionResultView(generic.DetailView):
    template_name = 'result.html'
    context_object_name = 'question'
    queryset = Question.objects.all()

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)
        context["result"] = "Right" if self.object.is_answer_choice_id_correct(
            int(request.POST["choice"])) else "Wrong"
        return self.render_to_response(context)


def answer_choices(request, pk):
    AnswerChoiceFormSet = formset_factory(AnswerChoiceForm)
    if request.method == 'POST':
        formset = AnswerChoiceFormSet(request.POST, request.FILES)
        if formset.is_valid():
            answer_choices = []
            for idx, c in zip(
                    range(len(formset.cleaned_data)),
                    formset.cleaned_data):
                answer_choices.append(dict(c, id=idx))
            question = Question.objects.get(id=pk)
            question.answer_choices = answer_choices
            question.save()
            return HttpResponseRedirect(
                reverse('quiz:detail', args=(pk,)))
    else:
        data = {
             'form-TOTAL_FORMS': '4',
             'form-INITIAL_FORMS': '4',
             'form-MAX_NUM_FORMS': '4',
             'form-MAX_NUM_FORMS': '4'
         }
        formset = AnswerChoiceFormSet(data)
    return render(request, 'answer_choices.html', {'formset': formset})


class QuestionDeleteView(generic.DeleteView):
    """
    Delete a Question
    """
    success_url = reverse_lazy('quiz:index')
    template_name_field = "question"
    model = Question

quiz2/views.py
from .forms import QuestionForm
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from .models import Question
from django.urls import reverse


def question_detail(request, pk):
    question = get_object_or_404(Question, pk=pk)
    if request.method == 'POST':
        form = QuestionForm(
            request.POST, request.FILES, instance=question)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('quiz2:index'))
    else:
        form = QuestionForm(instance=question)
    return render(
        request, 'quiz2/question_detail.html',
        {'form': form, "question": question})


def question_delete(request, pk):
    question = get_object_or_404(Question, pk=pk)
    question.delete()
    return HttpResponseRedirect(
            reverse('quiz2:index'))


def question_list(request):
    questions = Question.objects.all()
    if request.method == 'POST':
        form = QuestionForm(
            request.POST, request.FILES)
        if form.is_valid():
            new_form = form.save()
            return HttpResponseRedirect(
                reverse('quiz2:detail', args=(new_form.pk, )))
    else:
        form = QuestionForm()
    return render(
        request, 'quiz2/question_list.html',
        {'questions': questions, "form": form})

quiz/templates/answer_choices.html
{{ answer_choices }}

<form method="post" action="">
{% csrf_token %}
    <table>
        {{ formset }}
    </table>
    <input type="submit" value="Submit" />
</form>

quiz/templates/index.html
List of questions

<ol>
{% for question in questions %}

<li>
<a href="{% url 'quiz:detail' question.id %}">{{ question.text }}</a>
<a href="{% url 'quiz:delete' question.id %}">x</a>
</li>

{% endfor %}
</ol>

Post A Question

<form method="post" action ="{% url 'quiz:index' %}">
{% csrf_token %}

Question: <input type="text" name="text" required=True/>

<input type= "submit" value="Add"/>

</form>

quiz/templates/quiz/question_confirm_delete.html
are you sure you want to delete {{question.text}} <br />

<form method="post" action="">
{% csrf_token %}

    <input type="submit" value="YES" />
    <a href="{% url 'quiz:index' %}">no</a>
</form>

quiz/templates/quiz/question_detail.html
Question #{{ question.id }} <br/>

{{ question.text }} </br>

{% if not question.answer_choices|length %}
<a href="{% url 'quiz:choice' question.id %}">Add Answer Choices</a>
{% endif %}

<form method="post" action="{% url 'quiz:result' question.id %}">
{% csrf_token %}

{% for choice in question.answer_choices %}

<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" required/>
<label for="choice{{ forloop.counter }}">{{ choice.text }}</label><br />

{% endfor %}

{% if question.answer_choices|length %} <input type="submit" value="Check" /> {% endif %}

</form>

quiz/templates/result.html
You are {{ result }}<br />

{{ question.text }} <br />

{% for choice in question.answer_choices %}

{{choice.id }}.  "{{ choice.text }}" is {{ choice.correct }}
{% if  choice.id|stringformat:"i" == request.POST.choice %} (Your answer) {% endif %}<br />

{% endfor %}

Your answer is {{ request.POST.choice }}

quiz2/templates/quiz2/question_detail.html
{% load rest_framework %}

<html>
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
</head>
<body>

<h1>Question - {{ question.text }}</h1>

<form action="{% url 'quiz2:detail' pk=question.id%}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>

<form action="{% url 'quiz2:delete' pk=question.id%}" method="POST">
{% csrf_token %}
<input type="submit" value="Delete">
</form>

<a href="{% url 'quiz2:index' %}">Home</a>

</body></html>

quiz2/templates/quiz2/question_list.html
<html><body>
<h1>Questions</h1>
<ul>
    {% for question in questions %}
    <li><a href="{% url 'quiz2:detail' pk=question.id%}">{{ question.text }}</a></li>
    {% endfor %}
</ul>

<form action="{% url 'quiz2:index' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create Question">
</form>
</body></html>